---
# roles/bonjour/tasks/main.yml
# Author: Elimane GUEYE
# Description: Salutation
- include_tasks: "init.yml"
  tags: init

- name: Version 1.0.1 Bonjour {{ bonjour_prenom }} {{ bonjour_nom }}
  command: |
          echo Bonjour "{{ bonjour_prenom }}" "{{ bonjour_nom }}"
  register: bonjour_out
  changed_when: "'abcxyz' not in bonjour_out.stdout"
