---
- include_tasks: "init.yml"
  tags: init

- name: Version 1.0.0 Bonjour-Hi {{ bonjour_prenom }} {{ bonjour_nom }}
  command: |
          echo Bonjour-Hi "{{ bonjour_prenom }}" "{{ bonjour_nom }}"
  register: bonjour_out
  changed_when: "'abcxyz' not in bonjour_out.stdout"
